# Generated by Django 5.1 on 2024-11-05 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentName",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="اسم ولي الأمر",
                    ),
                ),
                (
                    "parentPhone",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهاتف المحمول الذي تم إدخاله ليس بالتنسيق الصحيح!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
