# Generated by Django 5.1 on 2024-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=20, verbose_name="اسم المدرسه"),
                ),
                (
                    "school_logo",
                    models.ImageField(
                        upload_to="manager/school_logo/", verbose_name="لوجو مدرسه"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="manager/school_logo/",
                        verbose_name=" ايقونة الموقع",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
            },
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subjectName",
                    models.CharField(max_length=100, verbose_name="اسم المادة"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="img/default_subject.jpg",
                        null=True,
                        upload_to="subjects/",
                        verbose_name="صورة المادة",
                    ),
                ),
            ],
        ),
    ]
