# Generated by Django 5.1 on 2024-11-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_grade",
                    models.CharField(
                        choices=[
                            ("إبتدائي", "إبتدائي"),
                            ("إعدادي", "إعدادي"),
                            ("ثانوي", "ثانوي"),
                        ],
                        max_length=50,
                        verbose_name="المرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "المرحلة الدراسية",
                "verbose_name_plural": "المراحل الدراسية",
            },
        ),
        migrations.CreateModel(
            name="GradeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gradename",
                    models.CharField(
                        choices=[
                            ("الصف الأول", "الصف الأول"),
                            ("الصف الثاني", "الصف الثاني"),
                            ("الصف الثالث", "الصف الثالث"),
                            ("الصف الرابع", "الصف الرابع"),
                            ("الصف الخامس", "الصف الخامس"),
                            ("الصف السادس", "الصف السادس"),
                            ("الصف السابع", "الصف السابع"),
                            ("الصف الثامن", "الصف الثامن"),
                            ("الصف التاسع", "الصف التاسع"),
                            ("الصف العاشر", "الصف العاشر"),
                            ("الصف الحادي عشر", "الصف الحادي عشر"),
                            ("الصف الثاني عشر", "الصف الثاني عشر"),
                        ],
                        max_length=50,
                        verbose_name="اسم الشعبة",
                    ),
                ),
                (
                    "class_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_names",
                        to="grades.classgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "الشعبة",
                "verbose_name_plural": "الشعب",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم الصف")),
                (
                    "grade_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="grades.gradename",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسم الصف",
                "verbose_name_plural": "الصفوف",
            },
        ),
    ]
